Fix TabTemplate equals method to directly access member.
This change updates the equals method in TabTemplate to compare the `mActiveTabContentId` member directly instead of using the getter method.

Using the getter was resulting in the following error in some cases:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at j$.util.Objects.requireNonNull
	at androidx.car.app.model.TabTemplate.getActiveTabContentId
	at androidx.car.app.model.TabTemplate.equals

Change-Id: Ia4e0b5bc6eb5aaf939b330cb1e52573cd94b2ae9