Suppress usage of deprecated DependencyFactory method
This method is deprecated in the latest gradle nightly build: https://github.com/gradle/gradle/blob/7ab7cf315d53c87eedcfa55f1f0b8da27a51acfc/subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/DependencyFactory.java#L94

Using the suggested replacement `createProjectDependency` causes a `NoSuchMethodError` in tests which use TEST_AGP_VERSION_8_2_1: https://github.com/androidx/androidx/actions/runs/24063571444/job/70184710985

Bug: 500315909
Bug: 500342472
Test: ./gradlew
Change-Id: Ife7afc1513213781ed63030ee7a5b34f85685b5f