Add AGP 9.2.0-alpha05 and Gradle 9.5.0-milestone7
AGP requires gradle to be 9.5.0-milestone5 to work

For the change in buildSrc/kotlin-dsl-dependency.gradle:
Gradle has split the gradle-kotlin-dsl dependency in Gradle 9.5.0 into multiple jars (e.g., gradle-kotlin-dsl-shared-runtime.jar, etc.)

The previous implementation of findGradleKotlinDsl() only fetched the main gradle-kotlin-dsl-<version>.jar. Because of this, the classes contained within the other gradle-kotlin-dsl jars (like org.gradle.kotlin.dsl.internal.sharedruntime.codegen.PluginEntryCache) were missing, resulting in `java.lang.NoClassDefFoundError` for the `:buildSrc-tests:test` task when upgrading to Gradle 9.5.0-milestone7

BUG: 495460240
TESTED: CI
Change-Id: Ibe7994cacc1300961838b9c3e98883234b0cce7e