Update the M3 dependencies
The M3 Catalog app failed to launch due to a NoClassDefFoundError
for the ForgetfulRetainScope.

- Removed alpha pinning from the Adaptive lib
- Added a collections dependency to the adaptive-navigation3 lib

Bug: 453730185
Test: Launched the Catalog app
Relnote: N/A
Change-Id: I3c4b351c4d83e963730984da839cad4fe59a4f29